In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data/imdb_1000.csv")

In [4]:
df.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [11]:
df[df['genre'] == 'Crime']

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Crime,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Crime,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Crime,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Crime,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Crime,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [13]:
df.query('genre == "Crime"')

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Crime,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Crime,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Crime,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Crime,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Crime,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [14]:
df.query("genre == 'Crime' & star_rating > 9")

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."

In [15]:
df.columns

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

In [16]:
df.dtypes

star_rating       float64
title              object
content_rating     object
genre              object
duration            int64
actors_list        object
dtype: object

In [18]:
df.query("genre == 'Crime' & star_rating > 9").sort_index(ascending=False)

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."

In [19]:
df.query("genre == 'Crime' & star_rating > 9").sort_index(axis=1)

,actors_list,content_rating,duration,genre,star_rating,title
0,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...",R,142,Crime,9.3,The Shawshank Redemption
1,"[u'Marlon Brando', u'Al Pacino', u'James Caan']",R,175,Crime,9.2,The Godfather
2,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv...",R,200,Crime,9.1,The Godfather: Part II

In [ ]:
# filter by multiple columns

In [36]:
df.query("genre == 'Crime' & star_rating > 8")

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Crime,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
292,8.1,The Manchurian Candidate,APPROVED,Crime,126,"[u'Frank Sinatra', u'Laurence Harvey', u'Janet..."
293,8.1,Duck Soup,PASSED,Crime,68,"[u'Groucho Marx', u'Harpo Marx', u'Chico Marx']"
294,8.1,Beauty and the Beast,G,Crime,84,"[u""Paige O'Hara"", u'Robby Benson', u'Richard W..."
295,8.1,The Truman Show,PG,Crime,103,"[u'Jim Carrey', u'Ed Harris', u'Laura Linney']"
296,8.1,The Wild Bunch,R,Crime,145,"[u'William Holden', u'Ernest Borgnine', u'Robe..."

In [ ]:
# Sort values by mutliple columns

In [38]:
df.query("genre == 'Crime'").sort_values(['star_rating', 'duration'])

,star_rating,title,content_rating,genre,duration,actors_list
938,7.4,Alice in Wonderland,G,Crime,75,"[u'Kathryn Beaumont', u'Ed Wynn', u'Richard Ha..."
948,7.4,Frances Ha,R,Crime,86,"[u'Greta Gerwig', u'Mickey Sumner', u'Adam Dri..."
966,7.4,The Simpsons Movie,PG-13,Crime,87,"[u'Dan Castellaneta', u'Julie Kavner', u'Nancy..."
947,7.4,Eraserhead,UNRATED,Crime,89,"[u'Jack Nance', u'Charlotte Stewart', u'Allen ..."
971,7.4,Death at a Funeral,R,Crime,90,"[u'Matthew Macfadyen', u'Peter Dinklage', u'Ew..."
...,...,...,...,...,...,...
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Crime,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
3,9.0,The Dark Knight,PG-13,Crime,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."

In [ ]:
# filter by contains string

In [39]:
df.query("genre == 'Crime' & content_rating.str.contains('PG')")

,star_rating,title,content_rating,genre,duration,actors_list
3,9.0,The Dark Knight,PG-13,Crime,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Crime,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
10,8.8,The Lord of the Rings: The Fellowship of the Ring,PG-13,Crime,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."
11,8.8,Inception,PG-13,Crime,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Crime,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
...,...,...,...,...,...,...
973,7.4,The Cider House Rules,PG-13,Crime,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
974,7.4,Tootsie,PG,Crime,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Crime,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Crime,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Crime,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."

In [47]:
df.query("genre.str.contains('Crime')")

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Crime,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Crime,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Crime,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Crime,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Crime,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [49]:
df.query("star_rating > 8 & genre.str.contains('Crime|Action')")

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Crime,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
292,8.1,The Manchurian Candidate,APPROVED,Crime,126,"[u'Frank Sinatra', u'Laurence Harvey', u'Janet..."
293,8.1,Duck Soup,PASSED,Crime,68,"[u'Groucho Marx', u'Harpo Marx', u'Chico Marx']"
294,8.1,Beauty and the Beast,G,Crime,84,"[u""Paige O'Hara"", u'Robby Benson', u'Richard W..."
295,8.1,The Truman Show,PG,Crime,103,"[u'Jim Carrey', u'Ed Harris', u'Laura Linney']"
296,8.1,The Wild Bunch,R,Crime,145,"[u'William Holden', u'Ernest Borgnine', u'Robe..."

In [50]:
teams = pd.DataFrame({'team': ['Cavs', 'Heat', 'Mavs', 'Mavs', 'Nets',
                            'Heat', 'Cavs', 'Jazz', 'Jazz', 'Hawks'],
                   'points': [3, 3, 4, 5, 4, 7, 8, 7, 12, 14],
                   'rebounds': [15, 14, 14, 10, 8, 14, 13, 9, 5, 4]})

In [51]:
teams

    team  points  rebounds
0   Cavs       3        15
1   Heat       3        14
2   Mavs       4        14
3   Mavs       5        10
4   Nets       4         8
5   Heat       7        14
6   Cavs       8        13
7   Jazz       7         9
8   Jazz      12         5
9  Hawks      14         4

In [55]:
teams.query("team == 'Cavs'")

   team  points  rebounds
0  Cavs       3        15
6  Cavs       8        13

In [58]:
teams.query("team.str.contains('Cavs|eat')")

   team  points  rebounds
0  Cavs       3        15
1  Heat       3        14
5  Heat       7        14
6  Cavs       8        13